### ISSUE TITLE
Missing `make reviewable` target

### ISSUE THREAD

**Issue by pierreprinetti** [crossplane-contrib/provider-openstack#52]
This repo's Github PR [template](https://github.com/crossplane-contrib/provider-openstack/blob/main/.github/PULL_REQUEST_TEMPLATE.md) mandates running `make reviewable test` prior to filing a PR. The linked [Contribution process](https://github.com/crossplane/crossplane/tree/master/contributing#checklist-cheat-sheet) similarly mentions `make reviewable`.

However, this repo's Makefile does not contain a `reviewable` target.

**Comment by jan-di** [comment]
This repo's Makefile does not, but the Makefile uses targets from upbound's [centralized build repository](https://github.com/upbound/build).

You need to run `make submodules` at least once before to initialize the git submodules, afterwards `make reviewable` will work. It's documented in the README, but not in the PR template (yet)

**Comment by jan-di** [comment]
Added a reference in the PR template. Feel free to reopen if something isn't working
