### ISSUE TITLE
Add security groups and network ports support

### ISSUE THREAD

**Issue by Ali-Gamal** [crossplane-contrib/provider-openstack#56]
The provider currently does not support managing security groups or network ports. This functionality is essential for effectively managing OpenStack resources.

https://registry.terraform.io/providers/terraform-provider-openstack/openstack/latest/docs/resources/networking_secgroup_rule_v2

https://registry.terraform.io/providers/terraform-provider-openstack/openstack/latest/docs/resources/networking_port_v2

**Comment by jan-di** [comment]
Hi, we are currently in the process to migrate this provider to upjet v1.0.0, which is a rather large change. When this is finished, we plan to add all the other missing resources that the terraform provider provides in a bulk change.

**Comment by Ali-Gamal** [comment]
Hi Jan-di, that sounds wonderful.

**Comment by schlakob** [comment]
The resources are now available on main branch. Until we release them you can already experiment with the prerelease version: 

xpkg.upbound.io/crossplane-contrib/provider-openstack:v0.2.0-49.g78e6609
